{
 "title": "Rates",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "# LightningFilter" } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dpdk_version_major{params=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Git",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dpdk_version_major{params=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dpdk_version_major{params=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log DP Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "dpdk_log_dp_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Eth Device",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dpdk_rx_good_bytes[$__interval])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(dpdk_tx_good_bytes[$__interval])*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Ether Device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(dpdk_rx_good_bytes[$__interval])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(dpdk_tx_good_bytes[$__interval])*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Worker Rates",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dpdk_rx_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(dpdk_tx_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "rate(dpdk_drop_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "Worker Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(dpdk_rx_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(dpdk_tx_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "rate(dpdk_drop_bytes{params=\"\"}[$__interval])*8",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "Valid Traffic Rate - Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dpdk_valid{params=\"\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Valid Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(dpdk_valid{params=\"\"}[$__interval])",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "Invalid Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(dpdk_duplicate{params=\"\"}[$__interval])",
     "legendFormat": "duplicate"
    },
    {
     "expr": "rate(dpdk_outdated_timestamp{params=\"\"}[$__interval])",
     "legendFormat": "outdated"
    },
    {
     "expr": "rate(dpdk_invalid_mac{params=\"\"}[$__interval])",
     "legendFormat": "invalid MAC"
    },
    {
     "expr": "rate(dpdk_invalid_hash{params=\"\"}[$__interval])",
     "legendFormat": "invalid hash"
    },
    {
     "expr": "rate(dpdk_ratelimiter_as{params=\"\"}[$__interval])",
     "legendFormat": "rate limited (AS)"
    },
    {
     "expr": "rate(dpdk_ratelimiter_overall{params=\"\"}[$__interval])",
     "legendFormat": "rate limited (Overall)"
    },
    {
     "expr": "rate(dpdk_error{params=\"\"}[$__interval])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(dpdk_rx_bytes{command=\"/lf/worker/stats\",params!=\"\"}[$__interval]) * 8",
     "legendFormat": "rx_{{params}}"
    }
   ]
  }
 ]
}