name: CI - Docker Build and Tests

on:
  push:
    branches: ["open-source"]
  pull_request:
    branches: ["open-source"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CI=true

  docker-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: lf-developer:latest
      - name: Start dev container
        run: ./docker.sh dev_create &&./docker.sh dev_up
      - name: Clear old artifacts
        run: rm -rf tmp/tests_artifacts
      - name: Run tests in dev container
        run: ./docker.sh dev_exec bash lightning-filter/tests.sh
      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-artifacts
          path: tmp/tests_artifacts
      - name: Stop dev container
        run: ./docker.sh dev_down
